
services:
  frontend:
    build: frontend/
    ports:
      - "3000:8080"
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bi
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: backend/
    ports:
      - "3000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bi
    volumes:
      - agentmodels:app/Agents/agent_models
  
  etl:
    build: etlinitdb/
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bi